version: '3'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb-container
    ports:
      - "27017:27017"
    networks:
      - my-network
    volumes:
      - mongodb-data:/data/db

  go-api:
    image: gabriel3035/ittalent-hackathon-go-api:latest
    depends_on:
      - mongodb
    container_name: go-api-container
    ports:
      - "9080:9080"
    networks:
      - my-network
    environment:
      - MONGO_DB_HOST=mongodb
    volumes:
      - ./go-mongo-crud-rest-api:/app

networks:
  my-network:
    driver: bridge

volumes:
  mongodb-data:
